"""indexes

Revision ID: b04a07162f7a
Revises: e8e6a5d0e13b
Create Date: 2026-06-22 20:57:28.255450
"""
from typing import Union
from collections.abc import Sequence

from alembic import op


revision: str = 'b04a07162f7a'
down_revision: str | None = 'e8e6a5d0e13b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_target_id'), 'audit_log', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_index(op.f('ix_device_device_type'), 'device', ['device_type'], unique=False)
    op.create_index(op.f('ix_device_group_id'), 'device', ['group_id'], unique=False)
    op.create_index(op.f('ix_device_ip'), 'device', ['ip'], unique=False)
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_index(op.f('ix_device_ip'), table_name='device')
    op.drop_index(op.f('ix_device_group_id'), table_name='device')
    op.drop_index(op.f('ix_device_device_type'), table_name='device')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_target_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    # ### end Alembic commands ###
