"""initial schema

Revision ID: e8e6a5d0e13b
Revises: 
Create Date: 2026-06-22 20:12:46.603761
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e8e6a5d0e13b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('target_kind', sa.Enum('device', 'controller', name='target_kind'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.Enum('ssh', 'telnet', 'snmp', 'tl1', name='protocol'), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('classification', sa.Enum('read', 'write', name='classification'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('ssh', 'telnet', 'snmp', 'api', 'tl1', name='credential_kind'), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=False),
    sa.Column('snmp_version', sa.Enum('v2c', 'v3', name='snmp_version'), nullable=True),
    sa.Column('snmp_v3_auth_protocol', sa.String(length=32), nullable=True),
    sa.Column('snmp_v3_priv_protocol', sa.String(length=32), nullable=True),
    sa.Column('snmp_v3_priv_secret', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.Enum('fiberhome_unm2000', name='controller_kind'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('default_ssh_credential_id', sa.Integer(), nullable=True),
    sa.Column('default_telnet_credential_id', sa.Integer(), nullable=True),
    sa.Column('default_snmp_credential_id', sa.Integer(), nullable=True),
    sa.Column('default_api_credential_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_api_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_snmp_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_ssh_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_telnet_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.Enum('routeros', 'huawei', 'cisco', name='device_type'), nullable=False),
    sa.Column('connection_mode', sa.Enum('direct', 'controller', name='connection_mode'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('ssh_enabled', sa.Boolean(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('ssh_credential_id', sa.Integer(), nullable=True),
    sa.Column('telnet_enabled', sa.Boolean(), nullable=False),
    sa.Column('telnet_port', sa.Integer(), nullable=False),
    sa.Column('telnet_credential_id', sa.Integer(), nullable=True),
    sa.Column('snmp_enabled', sa.Boolean(), nullable=False),
    sa.Column('snmp_port', sa.Integer(), nullable=False),
    sa.Column('snmp_credential_id', sa.Integer(), nullable=True),
    sa.Column('api_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_base_url', sa.String(length=255), nullable=False),
    sa.Column('api_credential_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['device_group.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snmp_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ssh_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['telnet_credential_id'], ['credential.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('device_group')
    op.drop_table('controller')
    op.drop_table('user')
    op.drop_table('credential')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
